/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        gib: {
          bg: '#F4F5F7',
          subtle: '#F4F5F7',
          hover: '#EDEEF2',
          border: '#E6E7EC',
          text: '#15161A',
          muted: '#565B66',
          brand: '#17407A',
          brandStrong: '#102D56',
          ice: '#9CC2E6',
          iceWash: '#E8F1FA',
          ink: '#14151F',
        },
        status: { red: '#B91C1C', amber: '#B45309', green: '#15803D' },
        prism: { mint: '#B4EAD0', sky: '#B9DBF7', lilac: '#CCC2FA', pink: '#F7C3D8', peach: '#FAD2BC' },
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border: 'hsl(var(--border))', input: 'hsl(var(--input))', ring: 'hsl(var(--ring))',
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))', foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))', 'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))', 'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))', ring: 'hsl(var(--sidebar-ring))',
        },
      },
      borderRadius: { md: '10px', lg: '14px', xl: '18px', '2xl': '22px' },
      fontFamily: {
        sans: ['var(--font-sans)', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', '"IBM Plex Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
        display: ['var(--font-sans)', 'Inter', 'system-ui', 'sans-serif'],
        serif: ['var(--font-serif)', 'Instrument Serif', 'Georgia', 'serif'],
      },
      fontSize: {
        micro: ['10px', { lineHeight: '14px', letterSpacing: '0.04em' }],
        meta: ['11px', { lineHeight: '16px' }], caption: ['12px', { lineHeight: '17px' }],
        body: ['13px', { lineHeight: '19px' }], bodyLg: ['14px', { lineHeight: '20px' }],
        lead: ['15px', { lineHeight: '22px' }], title: ['17px', { lineHeight: '24px' }],
        headline: ['20px', { lineHeight: '26px' }], stat: ['34px', { lineHeight: '1', letterSpacing: '-0.02em' }],
        displaySm: ['40px', { lineHeight: '1.05', letterSpacing: '-0.03em' }],
        display: ['56px', { lineHeight: '1.02', letterSpacing: '-0.035em' }],
        displayLg: ['72px', { lineHeight: '1.0', letterSpacing: '-0.04em' }],
        poster: ['clamp(44px, 8.5vw, 120px)', { lineHeight: '0.95', letterSpacing: '-0.03em' }],
        'mk-hero': ['clamp(40px, 5.6vw, 76px)', { lineHeight: '1.02', letterSpacing: '-0.035em' }],
        'mk-h2': ['clamp(32px, 4vw, 54px)', { lineHeight: '1.06', letterSpacing: '-0.03em' }],
        'mk-h3': ['clamp(24px, 2.4vw, 32px)', { lineHeight: '1.15', letterSpacing: '-0.02em' }],
        'mk-stat': ['clamp(44px, 5vw, 68px)', { lineHeight: '1', letterSpacing: '-0.035em' }],
        'mk-lead': ['clamp(17px, 1.4vw, 20px)', { lineHeight: '1.55' }],
        'mk-body': ['17px', { lineHeight: '1.6' }],
      },
      boxShadow: { card: '0 1px 2px rgba(16, 17, 26, 0.04), 0 8px 24px rgba(16, 17, 26, 0.06)' },
      keyframes: {
        'fade-up': { from: { opacity: '0', transform: 'translateY(6px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'word-in': { from: { opacity: '0', transform: 'translateY(2px)', filter: 'blur(3px)' }, to: { opacity: '1', transform: 'translateY(0)', filter: 'blur(0)' } },
        dot: { '0%, 80%, 100%': { opacity: '0.3', transform: 'translateY(0)' }, '40%': { opacity: '1', transform: 'translateY(-2px)' } },
        aurora: { from: { transform: 'translate3d(0, 0, 0) scale(1)' }, to: { transform: 'translate3d(8%, -6%, 0) scale(1.12)' } },
      },
      animation: {
        'fade-up': 'fade-up 260ms cubic-bezier(0.2, 0.8, 0.2, 1) both',
        'word-in': 'word-in 360ms ease-out both', dot: 'dot 1.2s ease-in-out infinite',
        aurora: 'aurora 12s ease-in-out infinite alternate',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
